services:
  postgres:
    container_name: nestjs-multi-tenancy
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_multi_tenancy
#      PGDATA: /data/postgres
#    volumes:
#      - ./data/pg:/data/postgres
